version: "3.9"
services:
  front-angular:
    build: ../demo-app # Replace with the NAME of your Angular project
    ports:
      - 4200:4200
    volumes:
      - "/app/node_modules"
      - "../demo-app/.:/app"
