version: "3.9"
services:
  front-angular:
    build: ../<front-angular> # Replace with the NAME of your Angular project
    ports:
      - 4200:4200
    volumes:
      - "/app/node_modules"
      - "../<FRONT_DIR_NAME>/.:/app"

  back-jsb:
    build: ../<back-jsb>
    ports:
      - 8080:8080
